#!/usr/bin/env bash
# Feature 0000031 req-001: planifest-zero/ renamed to planifest-zero/,
# every live reference updated. Historical records exempt.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FRAMEWORK="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO="$(cd "$FRAMEWORK/.." && pwd)"
source "$SCRIPT_DIR/helpers/assert.sh"

# Concatenated so repo-wide renames never rewrite this test's target string.
OLD_NAME="planifest""-framework"

echo "=== (a) folder is named planifest-zero ==="
assert_equals "planifest-zero" "$(basename "$FRAMEWORK")" "framework folder basename"
assert_equals "no" "$([ -d "$REPO/$OLD_NAME" ] && echo yes || echo no)" "old folder absent"

echo "=== (b) zero live references to the old name ==="
# plan/ is records (archive, changelog, backlog, and the change-in-progress
# artifacts that describe this very rename). CLAUDE.md is generated by setup.
# docs/decisions-index.md is a change record, exempt per the docs ADR.
HITS=$(grep -rl "$OLD_NAME" "$REPO" \
  --exclude-dir=.git --exclude-dir=.claude --exclude-dir=_temp \
  --exclude-dir=node_modules 2>/dev/null \
  | grep -v "$REPO/plan/\|$REPO/CLAUDE.md\|decisions-index.md" | wc -l | tr -d ' ')
assert_equals "0" "$HITS" "live files referencing the old name"

echo "=== (c) product.yml id is planifest-zero ==="
assert_equals "planifest-zero" "$(grep -E '^id:' "$REPO/product.yml" | sed 's/id: *"\{0,1\}\([^"]*\)"\{0,1\}/\1/' | tr -d ' ')" "product id"

echo "=== (d) refresh script renamed and portable ==="
assert_equals "no" "$([ -f "$REPO/refresh-$OLD_NAME-dir.ps1" ] && echo yes || echo no)" "old refresh script absent"
if [ -f "$REPO/refresh-planifest-zero-dir.ps1" ]; then
  assert_equals "0" "$(grep -c 'C:\\\\d\\\\planifest' "$REPO/refresh-planifest-zero-dir.ps1" || true)" "no hardcoded machine path"
  assert_contains "PSScriptRoot" "$(cat "$REPO/refresh-planifest-zero-dir.ps1")" "derives path from script location"
else
  assert_equals "renamed-or-deleted" "missing" "refresh script neither renamed nor deleted"
fi

echo "=== (e) .gitattributes has no dead skill-sync line ==="
assert_equals "0" "$(grep -c "skill-sync" "$FRAMEWORK/.gitattributes" || true)" "skill-sync attribute gone"

print_summary
